export const CommandButton = {
  Accelerator: "",
  AutoSize: false,
  BackColor: "red",
  BackStyle: 0,
  Cancel:false,
  Caption: "CommandButton1",
  ControlTipText: "helptext",
  Default: false,
  Enabled: true,
  Font: {
      FontName: "Arial",
      FontSize: 15,
      FontBold: false,
      FontItalic: false,
      FontUnderline:false,
      FontStrikethrough: true,
      FontStyle: "Arial Narrow Italic"
  },
  ForeColor: "#000000",
  Height: 30,
  HelpContextID:"0",
  Left:50,
  Locked:false,
  MouseIcon: "",
  MousePointer: 7,
  Name: "CommandButton1",
  ID: 1,
  Picture: "",
  PicturePosition: 7,
  TabIndex: 0,
  TabStop: true,
  Tag: "",
  TakeFocusOnClick: true,
  Top: 200,
  Visible: true,
  Width: 100,
  WordWrap: true
};
