export const Label = {
  Accelerator: "",
  AutoSize: false,
  BackColor: "red",
  BackStyle: 0,
  BorderColor: "#111111",
  BorderStyle: 1,
  Caption: "Label1",
  ControlTipText: "helptext",
  Enable: true,
  Font: {
      FontName: "Arial",
      FontSize: 15,
      FontBold: false,
      FontItalic: false,
      FontUnderline: false,
      FontStrikethrough: true,
      FontStyle: "Arial Narrow Italic"
  },
  ForeColor: "#000000",
  Height: 30,
  HelpContextID: "0",
  Left:50,
  MouseIcon: "",
  MousePointer: 7,
  Name: "Label1",
  ID: 1,
  Picture: "",
  PicturePosition: 7,
  SpecilalEffect: 0,
  TabIndex: 0,
  TabStop: true,
  Tag: "",
  TextAlign: 1,
  Top: 50,
  Visible: true,
  Width: 100,
  WordWrap: true
};
