
interface fdState {
  controlData: controlData,
  selectedControls: selectedControls
  userformData: any
}

interface controlData {
  properties: controlProperties,
  controls: controlData[],
  extraDatas: object | null,
  type: string
}


interface selectedControls {
  main: FdControlVue | FdControlVue[],
  selected: FdControlVue[]
}

interface controlProperties {
    [key: string]: any,
    Accelerator?: string,
    Alignment?: number,
    AutoSize?: boolean,
    AutoTab?: boolean,
    AutoWordSelect?: boolean,
    BackColor?: string,
    BackStyle?: number,
    BorderColor?: string,
    BorderStyle?: number,
    BoundColumn?: number,
    Cancel?: boolean,
    Caption?: string,
    ColumnCount?: number,
    ColumnHeads?: boolean,
    ColumnWidths?: string,
    ControlSource?: string,
    ControlTipText?: string,
    Cycle?: number,
    Default?: boolean,
    Delay?: number,
    DragBehavior?: number,
    DrawBuffer?: number,
    DropButtonStyle?: boolean,
    Enable?: boolean,
    EnterFieldBehavior?: boolean,
    Font?: font,
    ForeColor?: string,
    GroupName?: string,
    Height?: number,
    HelpContextID?: string,
    HideSelection?: boolean,
    ID?: number,
    IMEMode?: number,
    Index?: number,
    IntegralHeight?: boolean,
    KeepScrollBarsVisible?: number,
    LargeChange?: number,
    Left?: number,
    ListRows?: number,
    ListStyle?: number,
    ListWidth?: string,
    Locked?: boolean,
    MatchEntry?: number,
    MatchRequired?: boolean,
    Max?: number,
    MaxLength?: number,
    Min?: number,
    MouseIcon?: string,
    MousePointer?: number,
    MultiLine?: boolean,
    MultiRow?: boolean,
    MultiSelect?: number,
    Name?: string,
    Orientation?: number,
    PasswordChar?: string,
    Picture?: string,
    PictureAlignment?: number,
    PicturePosition?: number,
    PictureSizeMode?: number,
    PictureTiling?: boolean,
    ProportionalThumb?: boolean,
    RightToLeft?: boolean,
    RowSource?: string,
    ScrollBars?: number,
    ScrollHeight?: number,
    ScrollLeft?: number,
    ScrollTop?: number,
    ScrollWidth?: number,
    SelectionMargin?: boolean,
    ShowDropButtonWhen?: number,
    ShowModal?: boolean,
    SmallChange?: number,
    SpecilalEffect?: number,
    StartUpPosition?: number,
    Style?: number,
    TabFixedHeight?: number,
    TabFixedWidth?: number,
    TabIndex?: number,
    TabOrientation?: number,
    TabStop?: boolean,
    Tag?: string,
    TakeFocusOnClick?: boolean,
    Text?: string,
    TextAlign?: number,
    TextColumn?: number,
    Top?: number,
    TransitionEffect?: number,
    TransitionPeriod?: number,
    TripleState?: boolean,
    Value?: null | boolean | number | string,
    Visible?: boolean,
    WhatsThisButton?: boolean,
    WhatsThisHelp?: boolean,
    Width?: number,
    WordWrap?: boolean,
    Zoom?: number
}

interface extraData {
}

interface font {
}
